import { useState } from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'


export default function Home() {
  const [counter, setCounter] = useState(0);
  return (
    <>
      <Head>
        <title>Next.js Starter Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.buttonContainer}>
        <button onClick={() => setCounter(prev => prev - 1 <= 0 ? 0 : prev - 1)}>-</button>
        <h1>{counter}</h1>
        <button onClick={() => setCounter(prev => prev + 1)}>+</button>
      </div>
    </>
  )
}
